@startuml

package ch.ifocusit.example.domain.model.material <<Folder>> {
  class "Car"
  interface "Machine"
  interface "Vehicule"
  class "Wheel"
}

class "Car" {
  brand : String
  model : String
  drivers : Set<Driver>
  price : Price
  wheels : Collection<Wheel>
  addDriver(Driver) : Car
  addWheel(Wheel)
  buyBy(Driver, BigDecimal, Devise) : Driver
}

enum "Devise" {
  CHF
  EUR
  USD
}

class "Driver" {
  name : String
  cars : List<Car>
  addCar(Car)
  buy(Car)
}

class "Price" {
  amount : BigDecimal
  devise : Devise
}

interface "Vehicule"

class "Wheel"

"Car" --> "Devise" : use
"Car" "*" <-> "*" "Driver" : drivers/cars
"Car" --> "Price" : price
"Car" --> "*" "Wheel" : wheels
"Price" --> "Devise" : devise
"Vehicule" <|-- "Car"

@enduml