@startuml

package ch.ifocusit.plantuml.test.helper.domain.material <<Folder>> {
  class "Car"
  interface "Machine"
  interface "Vehicule"
  class "Wheel"
}

interface "Vehicule"

class "Car" {
  brand : String
  model : String
  driver : Driver
  price : Price
  wheels : Collection<Wheel>
  addWheel(Wheel)
  buyBy(Driver, BigDecimal, Devise) : Driver
}

class "Driver" {
  name : String
  cars : List<Car>
  buy(Car)
}

class "Price" {
  amount : BigDecimal
  devise : Devise
}

class "Wheel"

enum "Devise" {
  CHF
  EUR
  USD
}

"Vehicule" <|-- "Car"
"Car" "*" <-> "Driver" : driver
"Car" --> "Price" : price
"Car" --> "*" "Wheel" : wheels
"Price" --> "Devise" : devise
"Car" --> "Devise" : use

@enduml