@startuml

package Test #purple {
    class Test
}

interface Vehicule

class Car {
  brand : String
  model : String
  driver : Driver
  price : Price
  wheels : Collection<Wheel>
}

class Driver {
  name : String
  cars : List<Car>
}

class Price {
  amount : BigDecimal
  devise : Devise
}

class Wheel

enum Devise {
  CHF
  EUR
  USD
}

Vehicule <|-- Car
Car "*" <-> Driver : driver
Car --> Price : price
Car --> "*" Wheel : wheels
Price --> Devise : devise

@enduml