@startuml

class "Car" {
  brand : String
  model : String
  drivers : Set<Driver>
  price : Price
  wheels : Collection<Wheel>
  addWheel(Wheel)
  buyBy(Driver, BigDecimal, Devise) : Driver
}

"Car" --> "Devise" : use
"Car" --> "*" "Driver" : drivers
"Car" --> "Price" : price
"Car" --> "*" "Wheel" : wheels
"Vehicule" <|-- "Car"

@enduml