@startuml
skinparam backgroundColor lightgray
show methods
hide fields

header
class diagram type
endheader

title Service diagram

interface "AccessDataService" {
  whoDrive(Car, Instant) : Driver
}

"AccessDataService" --> "Car" : use
"AccessDataService" --> "Driver" : use

footer
page 1/1
endfooter

@enduml